build_task:
  name: android kernel build
  timeout_in: 120m
  trigger_type: manual
  # only_if: $CIRRUS_BRANCH == "main"
  container:
    image: ubuntu:20.04
    kvm: true
    cpu: 8
    memory: 24G
  env:
    GITHUB_TOKEN: ENCRYPTED[!955d3f2c7f14296d7a11295802fdd53d7b6d30ba3d46ef0a8017a86b74777930a07bf466946aa1856884ce54e357ee23!]
  prepare_script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y git curl sudo apt-utils tzdata
    - git clone https://${CIRRUS_REPO_OWNER}:${GITHUB_TOKEN}@github.com/${CIRRUS_REPO_OWNER}/android-kernel-patch.git android-kernel-patch
    - mv android-kernel-patch/*.sh .
    - cd android-kernel-patch && git rev-parse HEAD && cd ..
    - bash ./prepare.sh
  matrix:
    - name: arm64 common q-4.14 kernel build
      build_script: bash ./compile-arm64-common-kernel-q-4.14.sh
      publish_script: bash ./publish-arm64-common-kernel-q-4.14.sh
    - name: x86_64 common q-4.14 kernel build
      build_script: bash ./compile-x86_64-common-kernel-q-4.14.sh
      publish_script: bash ./publish-x86_64-common-kernel-q-4.14.sh
    - name: arm64 common s-5.10 kernel build
      build_script: bash ./compile-arm64-common-kernel-s-5.10.sh
      publish_script: bash ./publish-arm64-common-kernel-s-5.10.sh
    - name: x86_64 common s-5.10 kernel build
      build_script: bash ./compile-x86_64-common-kernel-s-5.10.sh
      publish_script: bash ./publish-x86_64-common-kernel-s-5.10.sh
    - name: arm64 emulator p kernel build
      build_script: bash ./compile-arm64-emulator-kernel-p.sh
      publish_script: bash ./publish-arm64-emulator-kernel-p.sh
    - name: arm64 emulator q kernel build
      build_script: bash ./compile-arm64-emulator-kernel-q.sh
      publish_script: bash ./publish-arm64-emulator-kernel-q.sh
    - name: x86_64 emulator p kernel build
      build_script: bash ./compile-x86_64-emulator-kernel-p.sh
      publish_script: bash ./publish-x86_64-emulator-kernel-p.sh
    - name: x86_64 emulator q kernel build
      build_script: bash ./compile-x86_64-emulator-kernel-q.sh
      publish_script: bash ./publish-x86_64-emulator-kernel-q.sh

run_task:
  name: android emulator run
  timeout_in: 120m
  # trigger_type: manual
  # only_if: $CIRRUS_BRANCH == "main"
  arm_container:
    image: ubuntu:20.04
    kvm: true
    cpu: 8
    memory: 24G
  prepare_script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y git curl sudo apt-utils tzdata
    - echo done.
    #- bash ./run-emulator.sh
